name: 'Pull Request Labeler'
description: 'Automatically label Pull Requests based on matching title prefix with configuration setup and base branch.'
author: 'Michal Mokros'
inputs:
  configuration-path:
    description: 'The path for the configuration of labels, default is .github/pull-request-labeler-config.yml'
    required: false
    default: '.github/pull-request-labeler-config.yml'
branding:
  icon: 'flag'
  color: 'purple'
runs:
  using: 'node12'
  main: 'index.js'