console.log("Hello Labeler");
console.log("Second try with node modules");
console.log("Third try with good function name");
console.log("Fourth try with load");
console.log("Fifth try with load");
console.log("Sixth try with load");
console.log("First try with new load");
console.log("Running again");
console.log("Running again");
console.log("Running again");
