name: 'Pull Request Labeler'
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr_labeler:
    runs-on: ubuntu-latest
    name: Labeling Pull Request
    steps:
    - name: Hello world action step
      id: hello
      uses: michalmokros/pull-request-labeler@fc8270502f1d007da2f7f95b9227dec34b23ed84
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}