name: 'Pull Request Labeler'
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr_labeler:
    runs-on: ubuntu-latest
    name: Pull Request Labeling
    steps:
    - name: Applying labels to Pull Request
      id: labeling-pr
      uses: michalmokros/pull-request-labeler@f3c6c4d68ed4a964cb6194a101124a98c7d170e8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}